CREATE TABLE Arvustused(
  ID INTEGER NOT NULL DEFAULT AUTOINCREMENT PRIMARY KEY,
  Hinnang TINYINT NOT NULL,
  Aeg DATETIME,
  Sisu VARCHAR(4096),
  Konto_ID INTEGER,
  FILM_ID INTEGER
);

CREATE TABLE Filmid(
  ID INTEGER NOT NULL DEFAULT AUTOINCREMENT PRIMARY KEY,
  Nimi VARCHAR(250) NOT NULL,
  Esilinastus DATE,
  Keskmine_antud_hinnang FLOAT,
  Kirjeldus VARHCAR(4096),
  Riik VARCHAR(3),
  Zanr VARCHAR(512),
  Stuudio_ID INTEGER,
  Hinnanguid INTEGER
);

CREATE TABLE Kontod(
  ID INTEGER NOT NULL DEFAULT AUTOINCREMENT PRIMARY KEY,
  Konto_nimi VARCHAR(32) UNIQUE NOT NULL,
  Paris_nimi VARCHAR(150),
  Liitumiskuupaev DATE,
  Keskmine_antud_hinnang FLOAT,
  Arvustusi INTEGER,
  Parool VARCHAR(16) NOT NULL
);

CREATE TABLE Lavastused(
  ID INTEGER NOT NULL DEFAULT AUTOINCREMENT PRIMARY KEY,
  Rezissoor_ID INTEGER,
  Film_ID INTEGER
);

CREATE TABLE Mangimised(
  ID INTEGER NOT NULL DEFAULT AUTOINCREMENT PRIMARY KEY,
  Roll_ID INTEGER,
  Naitleja_ID INTEGER
);

CREATE TABLE Naitlejad(
  ID INTEGER NOT NULL DEFAULT AUTOINCREMENT PRIMARY KEY,
  Nimi VARCHAR(150),
  Sunniriik VARCHAR(3),
  Sunnipaev DATE
);

CREATE TABLE Osalemised(
  ID INTEGER NOT NULL DEFAULT AUTOINCREMENT PRIMARY KEY,
  Roll_ID INTEGER,
  Film_ID INTEGER
);

CREATE TABLE Rezissoorid(
  ID INTEGER NOT NULL DEFAULT AUTOINCREMENT PRIMARY KEY,
  Nimi VARCHAR(150),
  Sunniriik VARCHAR(3),
  Sunnipaev DATE
);

CREATE TABLE Rollid(
  ID INTEGER NOT NULL DEFAULT AUTOINCREMENT PRIMARY KEY,
  Nimi VARCHAR(150),
  Kirjeldus VARCHAR(2048)
);

CREATE TABLE Stuudiod(
  ID INTEGER NOT NULL DEFAULT AUTOINCREMENT PRIMARY KEY,
  Nimi VARCHAR(250) NOT NULL,
  Riik VARCHAR(3),
);

// Eraldi on loodud ka võtmed relatsioonide vahel. Need on vaadeldavad
// andmebaasis endas ja ON DELETE/UPDATE osa nähtav System Triggers all.